witnessmenow/ESP32-Cheap-Yellow-Display

Examples/ESPHome/1-Helloworld/yellowtft1.yaml, Examples/ESPHome/2-ESPHomeClock/yellowtft1.yaml, Examples/ESPHome/4-TouchDemo/yellowtft1.yaml
Newest version of ESPHome auto fallback to 8 bit so my custom palette setup is no longer needed.
=> Update ESPHome examples

PROJECTS.md
This PR is a follow up on the project I shared on Discord. I'm not expecting the code to mutate as much at this point, so I'd like to share it in `PROJECTS.md`. It's MIT-licensed, and does what it says on the tin.
=> Add my own project, ESP32-fluid-simulation, to PROJECTS.md

Examples/Basics/7-HelloRadio/7-HelloRadio.ino
Added retry logic if connection to radio station fails.
=> HelloRadio - Add retry logic

PROJECTS.md
Adds links to `PROJECTS.md` to the ESP32-TV project - https://github.com/atomic14/esp32-tv
=> Adds ESP32-TV project

Examples/ESPHome/1-Helloworld/yellowtft1.yaml, Examples/ESPHome/6-VariousFeatures/yellowtft1.yaml
Example for ESPHome for board with 2 USB ports using most of the features of the board.
=> Add ESPHome template with all features.

README.md
Could not find the screen size in the README, so I added it.
=> Add screen size to README.md

Examples/LVGL/LVGL_Arduino/LVGL_Arduino.ino, Examples/LVGL/README.md, Examples/LVGL/lv_conf.h
Minor changes to the official LVGL example sketch and a README to help with setting up LVGL on a CYD.
=> Working LVGL example sketch

Examples/Showcases/1-Slideshow/1-Slideshow.ino, Examples/Showcases/1-Slideshow/platformio.ini
Add a new, more complex example to create a slideshow from JPGs on a SD card
=> Add SD card slideshow example

README.md
=> Add German Translation

Examples/openHASP/README.md
Some brief documentation about using openHASP on the CYD
=> openHASP documentation

Examples/openHASP/README.md
Added some more information, sorted out a bit of formatting and fixed some typos
=> Update information about openHASP on the CYD

.github/pages/cyd.json, .github/pages/index.html, .github/pages/manifest.json, .github/workflows/main.yml, Examples/Basics/3-SDCardTest/platformio.ini, Examples/Basics/6-LEDTest/platformio.ini
* Builds als folders containing a platformio.ini
* Create a page zu flash CYD or CYD2USB using the web flasher
Not super nice yet, but works.
=> Add github actions for building the examples and creating a web flasher page

Examples/Showcases/1-Slideshow/1-Slideshow.ino, Examples/Showcases/1-Slideshow/platformio.ini
Add touch to slide show example (using bitbang library)
=> Add touch support to slideshow examples

Examples/Micropython/Micropython.md, Examples/Micropython/demo.py
Here's some example code for using the Cheap Yellow Display with Micropython
=> Added Micropython example

Examples/ESPHome/4-TouchDemo/yellowtft1.yaml, Examples/ESPHome/6-VariousFeatures/yellowtft1.yaml, Examples/ESPHome/7-ExtendedTouchDemo/yellowtft1.yaml
See https://github.com/esphome/esphome-docs/commit/5cc4b6769664d1e218a31e64c4cd8ea675fbfba6
=> fix: upgrade to esphome 2023.12 API

Examples/ESPHome/README.md
Documentation ;) Save others from looking through the commits to determine what the additional examples do
=> Update README.md for ESPHome examples

Examples/LVGL9/platformio.ini
Add PIO support for the LVGL9 example
=> Add platformio.ini for LVGL9 example

3dModels/README.md
Hi,
just letting you know that these two internal links are broken.
=> Fix two broken links in 3dModels/README.md

DisplayConfig/CYD2USB/User_Setup.h, Examples/Basics/1-HelloWorld/platformio.ini, Examples/Basics/2-TouchTest/platformio.ini, Examples/Basics/4-BacklightControlTest/platformio.ini, Examples/Basics/5-LDRTest/platformio.ini, Examples/Basics/8-Buttons/8-Buttons.ino, Examples/Basics/8-Buttons/platformio.ini
Added a new exampleusing TFT_eSPI buttons with bitbang touch library
=> Add TFT_eSPI button example

README.md
Brian suggested a while back adding a link to this example.
=> Add link to Cyd2U example to README.md

Examples/Projects/RollingClockWithWifiManager/RollingClockWithWifiManager/RollingClockLogic.h
Update prevDay to fix the condition
=> fix blinking date

TROUBLESHOOTING.md
Suggestion of entry in troubleshooting section regarding `brltty` and uploading problems on Ubuntu and flavors.
=> trouble shooting upload on Ubuntu and flavors

Examples/ESPHome/1-Helloworld/yellowtft1.yaml, Examples/ESPHome/2-ESPHomeClock/yellowtft1.yaml, Examples/ESPHome/3-RGBLED/yellowtft1.yaml, Examples/ESPHome/4-TouchDemo/yellowtft1.yaml, Examples/ESPHome/5-TemperatureGraph/yellowtft1.yaml, Examples/ESPHome/6-VariousFeatures/yellowtft1.yaml, Examples/ESPHome/7-ExtendedTouchDemo/yellowtft1.yaml
ESPHome has changed ota to require platform.
=> Added platform to ota

PROJECTS.md
Added my project, which is under MIT license, to the PROJECTS.md file.
=> Added PhilRadio to PROJECTS.md

PROJECTS.md
Adding my project [esp-cyd-mcp](https://github.com/OfryL/esp-cyd-mcp) to the projects list
=> Adding ESP CYD MCP project

Examples/Projects/LeetCodeDailyQuestion/LeetCodeDailyQuestion.ino, Examples/Projects/LeetCodeDailyQuestion/README.md
=> feat: add LeetCode daily question viewer with auto-scroll and touch toggle

Mods/README.md
Simple typo fix, "use use" instead of "use"
=> Fixed Typo
